language: bash
services: docker

env:
  - VERSION=jdk-6 DOCKERDIR=jdk-6
  - VERSION=jdk-7 DOCKERDIR=jdk-7
  - VERSION=jdk-8 DOCKERDIR=jdk-8
  - VERSION=jdk-9 DOCKERDIR=jdk-9

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="yongjhih/gradle:$VERSION"
  - dockerdir="${DOCKERDIR:-.}"

script:
  - docker build -t "$image" "$dockerdir"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
